In [16]:
import pandas as pd

In [17]:
import numpy as np

In [18]:
from mayavi import mlab

In [19]:
df = pd.read_csv("Results_80.csv").drop(columns=["Unnamed: 0"])

In [20]:
Ro = 69.634*1E9
Rss = 2.5 * Ro

X = np.array(df['X'])
Y = np.array(df['Y'])
Z = np.array(df['Z'])

R = np.array(df['R'])
Theta = np.array(df['Theta'])
Phi = np.array(df['Phi'])

B_radial = np.array(df['B_Radial'])
B_theta = np.array(df['B_Theta'])
B_phi = np.array(df['B_Phi'])

In [21]:
BX =  ( B_radial*np.sin(Theta)*np.cos(Phi) ) + ( B_theta*np.cos(Theta)*np.cos(Phi) ) - ( B_phi*np.sin(Theta) ) 

In [22]:
BY = ( B_radial*np.sin(Theta)*np.sin(Phi) ) + ( B_theta*np.cos(Theta)*np.sin(Phi) ) - ( B_phi*np.cos(Theta) ) 

In [23]:
BZ = ( B_radial*np.cos(Theta) )  - ( B_theta*np.sin(Theta) )

In [24]:
condition_index = np.where((R>Ro) & (R<2.5*Ro))[0]

In [10]:
B = np.sqrt(BX**2 + BY**2 + BZ**2)

In [11]:
phi, theta = np.mgrid[0:np.pi:100j, 0:2*np.pi:100j]
x = Ro*np.sin(phi) * np.cos(theta)
y = Ro*np.sin(phi) * np.sin(theta)
z = Ro*np.cos(phi)
mlab.mesh(x, y, z)
mlab.mesh(x, y, z, representation='surface',color = (0,0,0))
s= mlab.quiver3d(X[condition_index],Y[condition_index],Z[condition_index],BX[condition_index], BY[condition_index], BZ[condition_index],line_width=2,vmax=B.max(),vmin = B.min())
mlab.show()

In [28]:
df['BX'] = BX
df['BY'] = BY
df['BZ'] = BZ
df['Mag'] = B


df = df.drop(columns = ['B_Radial' , 'B_Theta' , 'B_Phi' , 'Mag' , 'R' , 'Theta' , 'Phi'  ])

In [29]:
df.to_csv("Results_All_Components80.csv")

In [30]:
df

X             Y             Z   BX   BY   BZ
0      -2.089020e+11 -2.089020e+11 -2.089020e+11  0.0  0.0 -0.0
1      -2.089020e+11 -2.089020e+11 -2.036133e+11  0.0  0.0 -0.0
2      -2.089020e+11 -2.089020e+11 -1.983247e+11  0.0  0.0 -0.0
3      -2.089020e+11 -2.089020e+11 -1.930360e+11  0.0  0.0 -0.0
4      -2.089020e+11 -2.089020e+11 -1.877474e+11  0.0  0.0 -0.0
...              ...           ...           ...  ...  ...  ...
511995  2.089020e+11  2.089020e+11  1.877474e+11  0.0  0.0  0.0
511996  2.089020e+11  2.089020e+11  1.930360e+11  0.0  0.0  0.0
511997  2.089020e+11  2.089020e+11  1.983247e+11  0.0  0.0  0.0
511998  2.089020e+11  2.089020e+11  2.036133e+11  0.0  0.0  0.0
511999  2.089020e+11  2.089020e+11  2.089020e+11  0.0  0.0  0.0

[512000 rows x 6 columns]

In [22]:
import numpy as np

phi = np.linspace(0,2*np.pi,10)
theta = np.linspace(0,np.pi,10)
u = np.random.rand(10)

Ro = 69.634*1E9
Rss = 2.5 * Ro

r = (3*Ro) * np.cbrt(u)

In [23]:
x = r * np.sin( theta) * np.cos( phi )
y = r * np.sin( theta) * np.sin( phi )
z = r * np.cos( theta )

In [24]:
x

array([ 0.00000000e+00,  4.20614663e+10,  2.00245710e+10, -5.11450182e+10,
       -1.78713027e+11, -1.47215702e+11, -3.63612354e+10,  1.47294524e+10,
        3.14084546e+10,  2.42540381e-05])

In [25]:
r

array([1.31647146e+11, 1.60538336e+11, 1.79401262e+11, 1.18114360e+11,
       1.93116301e+11, 1.59080467e+11, 8.39726761e+10, 1.31961995e+11,
       1.19878394e+11, 1.98049251e+11])

In [26]:
u

array([0.25026871, 0.45384596, 0.63335716, 0.18075083, 0.79000349,
       0.44159361, 0.06495105, 0.25206865, 0.18897091, 0.85210246])